apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-task-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-task-manager
  template:
    metadata:
      labels:
        app: fastapi-task-manager
    spec:

      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;

      containers:
        - name: fastapi
          image: robertadamyan/fastapi-task-manager:46165c8
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: DB_PORT

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
